// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"teslatrack/internal/biz"
	"teslatrack/internal/conf"
	"teslatrack/internal/data"
	"teslatrack/internal/server"
	"teslatrack/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	authorizeTokenRepo := data.NewAuthorizeTokenRepo(dataData)
	authorizeTokenUsecase := biz.NewAuthorizeTokenUsecase(authorizeTokenRepo, confServer, logger)
	redirector := server.NewRedirector(confServer, authorizeTokenUsecase)
	authorizeRepo := data.NewAuthorizeRepo(dataData)
	authorizeUsecase := biz.NewAuthorizeUsecase(authorizeRepo, confServer, logger)
	authorizeService := service.NewAuthorizeService(authorizeUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, redirector, authorizeService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
