// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"teslatrack/internal/data/ent/authorize"
	"teslatrack/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuthorizeDelete is the builder for deleting a Authorize entity.
type AuthorizeDelete struct {
	config
	hooks    []Hook
	mutation *AuthorizeMutation
}

// Where appends a list predicates to the AuthorizeDelete builder.
func (_d *AuthorizeDelete) Where(ps ...predicate.Authorize) *AuthorizeDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AuthorizeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AuthorizeDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AuthorizeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(authorize.Table, sqlgraph.NewFieldSpec(authorize.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AuthorizeDeleteOne is the builder for deleting a single Authorize entity.
type AuthorizeDeleteOne struct {
	_d *AuthorizeDelete
}

// Where appends a list predicates to the AuthorizeDelete builder.
func (_d *AuthorizeDeleteOne) Where(ps ...predicate.Authorize) *AuthorizeDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AuthorizeDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{authorize.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AuthorizeDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
