// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"teslatrack/internal/data/ent/authorize"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Authorize is the model entity for the Authorize schema.
type Authorize struct {
	config
	// ID of the ent.
	ID           int `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Authorize) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case authorize.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Authorize fields.
func (_m *Authorize) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case authorize.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Authorize.
// This includes values selected through modifiers, order, etc.
func (_m *Authorize) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Authorize.
// Note that you need to call Authorize.Unwrap() before calling this method if this Authorize
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Authorize) Update() *AuthorizeUpdateOne {
	return NewAuthorizeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Authorize entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Authorize) Unwrap() *Authorize {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Authorize is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Authorize) String() string {
	var builder strings.Builder
	builder.WriteString("Authorize(")
	builder.WriteString(fmt.Sprintf("id=%v", _m.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Authorizes is a parsable slice of Authorize.
type Authorizes []*Authorize
