// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"teslatrack/internal/data/ent/authorizetoken"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuthorizeTokenCreate is the builder for creating a AuthorizeToken entity.
type AuthorizeTokenCreate struct {
	config
	mutation *AuthorizeTokenMutation
	hooks    []Hook
}

// SetTeslaCode sets the "tesla_code" field.
func (_c *AuthorizeTokenCreate) SetTeslaCode(v string) *AuthorizeTokenCreate {
	_c.mutation.SetTeslaCode(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *AuthorizeTokenCreate) SetClientID(v string) *AuthorizeTokenCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetClientSecret sets the "client_secret" field.
func (_c *AuthorizeTokenCreate) SetClientSecret(v string) *AuthorizeTokenCreate {
	_c.mutation.SetClientSecret(v)
	return _c
}

// SetAccessToken sets the "access_token" field.
func (_c *AuthorizeTokenCreate) SetAccessToken(v string) *AuthorizeTokenCreate {
	_c.mutation.SetAccessToken(v)
	return _c
}

// SetRefreshToken sets the "refresh_token" field.
func (_c *AuthorizeTokenCreate) SetRefreshToken(v string) *AuthorizeTokenCreate {
	_c.mutation.SetRefreshToken(v)
	return _c
}

// SetScope sets the "scope" field.
func (_c *AuthorizeTokenCreate) SetScope(v string) *AuthorizeTokenCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuthorizeTokenCreate) SetCreatedAt(v time.Time) *AuthorizeTokenCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuthorizeTokenCreate) SetNillableCreatedAt(v *time.Time) *AuthorizeTokenCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AuthorizeTokenCreate) SetUpdatedAt(v time.Time) *AuthorizeTokenCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AuthorizeTokenCreate) SetNillableUpdatedAt(v *time.Time) *AuthorizeTokenCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeleted sets the "deleted" field.
func (_c *AuthorizeTokenCreate) SetDeleted(v bool) *AuthorizeTokenCreate {
	_c.mutation.SetDeleted(v)
	return _c
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (_c *AuthorizeTokenCreate) SetNillableDeleted(v *bool) *AuthorizeTokenCreate {
	if v != nil {
		_c.SetDeleted(*v)
	}
	return _c
}

// Mutation returns the AuthorizeTokenMutation object of the builder.
func (_c *AuthorizeTokenCreate) Mutation() *AuthorizeTokenMutation {
	return _c.mutation
}

// Save creates the AuthorizeToken in the database.
func (_c *AuthorizeTokenCreate) Save(ctx context.Context) (*AuthorizeToken, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuthorizeTokenCreate) SaveX(ctx context.Context) *AuthorizeToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthorizeTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthorizeTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuthorizeTokenCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := authorizetoken.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := authorizetoken.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Deleted(); !ok {
		v := authorizetoken.DefaultDeleted
		_c.mutation.SetDeleted(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuthorizeTokenCreate) check() error {
	if _, ok := _c.mutation.TeslaCode(); !ok {
		return &ValidationError{Name: "tesla_code", err: errors.New(`ent: missing required field "AuthorizeToken.tesla_code"`)}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "AuthorizeToken.client_id"`)}
	}
	if _, ok := _c.mutation.ClientSecret(); !ok {
		return &ValidationError{Name: "client_secret", err: errors.New(`ent: missing required field "AuthorizeToken.client_secret"`)}
	}
	if _, ok := _c.mutation.AccessToken(); !ok {
		return &ValidationError{Name: "access_token", err: errors.New(`ent: missing required field "AuthorizeToken.access_token"`)}
	}
	if _, ok := _c.mutation.RefreshToken(); !ok {
		return &ValidationError{Name: "refresh_token", err: errors.New(`ent: missing required field "AuthorizeToken.refresh_token"`)}
	}
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "AuthorizeToken.scope"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuthorizeToken.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AuthorizeToken.updated_at"`)}
	}
	if _, ok := _c.mutation.Deleted(); !ok {
		return &ValidationError{Name: "deleted", err: errors.New(`ent: missing required field "AuthorizeToken.deleted"`)}
	}
	return nil
}

func (_c *AuthorizeTokenCreate) sqlSave(ctx context.Context) (*AuthorizeToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuthorizeTokenCreate) createSpec() (*AuthorizeToken, *sqlgraph.CreateSpec) {
	var (
		_node = &AuthorizeToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(authorizetoken.Table, sqlgraph.NewFieldSpec(authorizetoken.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TeslaCode(); ok {
		_spec.SetField(authorizetoken.FieldTeslaCode, field.TypeString, value)
		_node.TeslaCode = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(authorizetoken.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.ClientSecret(); ok {
		_spec.SetField(authorizetoken.FieldClientSecret, field.TypeString, value)
		_node.ClientSecret = value
	}
	if value, ok := _c.mutation.AccessToken(); ok {
		_spec.SetField(authorizetoken.FieldAccessToken, field.TypeString, value)
		_node.AccessToken = value
	}
	if value, ok := _c.mutation.RefreshToken(); ok {
		_spec.SetField(authorizetoken.FieldRefreshToken, field.TypeString, value)
		_node.RefreshToken = value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(authorizetoken.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(authorizetoken.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(authorizetoken.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Deleted(); ok {
		_spec.SetField(authorizetoken.FieldDeleted, field.TypeBool, value)
		_node.Deleted = value
	}
	return _node, _spec
}

// AuthorizeTokenCreateBulk is the builder for creating many AuthorizeToken entities in bulk.
type AuthorizeTokenCreateBulk struct {
	config
	err      error
	builders []*AuthorizeTokenCreate
}

// Save creates the AuthorizeToken entities in the database.
func (_c *AuthorizeTokenCreateBulk) Save(ctx context.Context) ([]*AuthorizeToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuthorizeToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthorizeTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuthorizeTokenCreateBulk) SaveX(ctx context.Context) []*AuthorizeToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthorizeTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthorizeTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
