// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"teslatrack/internal/data/ent/authorize"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Authorize is the model entity for the Authorize schema.
type Authorize struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 客户端ID
	ClientID string `json:"client_id,omitempty"`
	// 客户端密钥
	ClientSecret string `json:"client_secret,omitempty"`
	// 授权类型
	GrantType string `json:"grant_type,omitempty"`
	// 重定向URI
	RedirectURI string `json:"redirect_uri,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 是否删除
	Deleted      bool `json:"deleted,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Authorize) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case authorize.FieldDeleted:
			values[i] = new(sql.NullBool)
		case authorize.FieldID:
			values[i] = new(sql.NullInt64)
		case authorize.FieldClientID, authorize.FieldClientSecret, authorize.FieldGrantType, authorize.FieldRedirectURI:
			values[i] = new(sql.NullString)
		case authorize.FieldCreatedAt, authorize.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Authorize fields.
func (_m *Authorize) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case authorize.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case authorize.FieldClientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value.Valid {
				_m.ClientID = value.String
			}
		case authorize.FieldClientSecret:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_secret", values[i])
			} else if value.Valid {
				_m.ClientSecret = value.String
			}
		case authorize.FieldGrantType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field grant_type", values[i])
			} else if value.Valid {
				_m.GrantType = value.String
			}
		case authorize.FieldRedirectURI:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field redirect_uri", values[i])
			} else if value.Valid {
				_m.RedirectURI = value.String
			}
		case authorize.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case authorize.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case authorize.FieldDeleted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field deleted", values[i])
			} else if value.Valid {
				_m.Deleted = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Authorize.
// This includes values selected through modifiers, order, etc.
func (_m *Authorize) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Authorize.
// Note that you need to call Authorize.Unwrap() before calling this method if this Authorize
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Authorize) Update() *AuthorizeUpdateOne {
	return NewAuthorizeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Authorize entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Authorize) Unwrap() *Authorize {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Authorize is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Authorize) String() string {
	var builder strings.Builder
	builder.WriteString("Authorize(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("client_id=")
	builder.WriteString(_m.ClientID)
	builder.WriteString(", ")
	builder.WriteString("client_secret=")
	builder.WriteString(_m.ClientSecret)
	builder.WriteString(", ")
	builder.WriteString("grant_type=")
	builder.WriteString(_m.GrantType)
	builder.WriteString(", ")
	builder.WriteString("redirect_uri=")
	builder.WriteString(_m.RedirectURI)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted=")
	builder.WriteString(fmt.Sprintf("%v", _m.Deleted))
	builder.WriteByte(')')
	return builder.String()
}

// Authorizes is a parsable slice of Authorize.
type Authorizes []*Authorize
