// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"teslatrack/internal/data/ent/authorize"
	"teslatrack/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuthorizeUpdate is the builder for updating Authorize entities.
type AuthorizeUpdate struct {
	config
	hooks    []Hook
	mutation *AuthorizeMutation
}

// Where appends a list predicates to the AuthorizeUpdate builder.
func (_u *AuthorizeUpdate) Where(ps ...predicate.Authorize) *AuthorizeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *AuthorizeUpdate) SetClientID(v string) *AuthorizeUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *AuthorizeUpdate) SetNillableClientID(v *string) *AuthorizeUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetClientSecret sets the "client_secret" field.
func (_u *AuthorizeUpdate) SetClientSecret(v string) *AuthorizeUpdate {
	_u.mutation.SetClientSecret(v)
	return _u
}

// SetNillableClientSecret sets the "client_secret" field if the given value is not nil.
func (_u *AuthorizeUpdate) SetNillableClientSecret(v *string) *AuthorizeUpdate {
	if v != nil {
		_u.SetClientSecret(*v)
	}
	return _u
}

// SetGrantType sets the "grant_type" field.
func (_u *AuthorizeUpdate) SetGrantType(v string) *AuthorizeUpdate {
	_u.mutation.SetGrantType(v)
	return _u
}

// SetNillableGrantType sets the "grant_type" field if the given value is not nil.
func (_u *AuthorizeUpdate) SetNillableGrantType(v *string) *AuthorizeUpdate {
	if v != nil {
		_u.SetGrantType(*v)
	}
	return _u
}

// SetRedirectURI sets the "redirect_uri" field.
func (_u *AuthorizeUpdate) SetRedirectURI(v string) *AuthorizeUpdate {
	_u.mutation.SetRedirectURI(v)
	return _u
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_u *AuthorizeUpdate) SetNillableRedirectURI(v *string) *AuthorizeUpdate {
	if v != nil {
		_u.SetRedirectURI(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuthorizeUpdate) SetUpdatedAt(v time.Time) *AuthorizeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeleted sets the "deleted" field.
func (_u *AuthorizeUpdate) SetDeleted(v bool) *AuthorizeUpdate {
	_u.mutation.SetDeleted(v)
	return _u
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (_u *AuthorizeUpdate) SetNillableDeleted(v *bool) *AuthorizeUpdate {
	if v != nil {
		_u.SetDeleted(*v)
	}
	return _u
}

// Mutation returns the AuthorizeMutation object of the builder.
func (_u *AuthorizeUpdate) Mutation() *AuthorizeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthorizeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthorizeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuthorizeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthorizeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuthorizeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := authorize.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AuthorizeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(authorize.Table, authorize.Columns, sqlgraph.NewFieldSpec(authorize.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(authorize.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientSecret(); ok {
		_spec.SetField(authorize.FieldClientSecret, field.TypeString, value)
	}
	if value, ok := _u.mutation.GrantType(); ok {
		_spec.SetField(authorize.FieldGrantType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RedirectURI(); ok {
		_spec.SetField(authorize.FieldRedirectURI, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(authorize.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Deleted(); ok {
		_spec.SetField(authorize.FieldDeleted, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authorize.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuthorizeUpdateOne is the builder for updating a single Authorize entity.
type AuthorizeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthorizeMutation
}

// SetClientID sets the "client_id" field.
func (_u *AuthorizeUpdateOne) SetClientID(v string) *AuthorizeUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *AuthorizeUpdateOne) SetNillableClientID(v *string) *AuthorizeUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetClientSecret sets the "client_secret" field.
func (_u *AuthorizeUpdateOne) SetClientSecret(v string) *AuthorizeUpdateOne {
	_u.mutation.SetClientSecret(v)
	return _u
}

// SetNillableClientSecret sets the "client_secret" field if the given value is not nil.
func (_u *AuthorizeUpdateOne) SetNillableClientSecret(v *string) *AuthorizeUpdateOne {
	if v != nil {
		_u.SetClientSecret(*v)
	}
	return _u
}

// SetGrantType sets the "grant_type" field.
func (_u *AuthorizeUpdateOne) SetGrantType(v string) *AuthorizeUpdateOne {
	_u.mutation.SetGrantType(v)
	return _u
}

// SetNillableGrantType sets the "grant_type" field if the given value is not nil.
func (_u *AuthorizeUpdateOne) SetNillableGrantType(v *string) *AuthorizeUpdateOne {
	if v != nil {
		_u.SetGrantType(*v)
	}
	return _u
}

// SetRedirectURI sets the "redirect_uri" field.
func (_u *AuthorizeUpdateOne) SetRedirectURI(v string) *AuthorizeUpdateOne {
	_u.mutation.SetRedirectURI(v)
	return _u
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_u *AuthorizeUpdateOne) SetNillableRedirectURI(v *string) *AuthorizeUpdateOne {
	if v != nil {
		_u.SetRedirectURI(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuthorizeUpdateOne) SetUpdatedAt(v time.Time) *AuthorizeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeleted sets the "deleted" field.
func (_u *AuthorizeUpdateOne) SetDeleted(v bool) *AuthorizeUpdateOne {
	_u.mutation.SetDeleted(v)
	return _u
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (_u *AuthorizeUpdateOne) SetNillableDeleted(v *bool) *AuthorizeUpdateOne {
	if v != nil {
		_u.SetDeleted(*v)
	}
	return _u
}

// Mutation returns the AuthorizeMutation object of the builder.
func (_u *AuthorizeUpdateOne) Mutation() *AuthorizeMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuthorizeUpdate builder.
func (_u *AuthorizeUpdateOne) Where(ps ...predicate.Authorize) *AuthorizeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthorizeUpdateOne) Select(field string, fields ...string) *AuthorizeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Authorize entity.
func (_u *AuthorizeUpdateOne) Save(ctx context.Context) (*Authorize, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthorizeUpdateOne) SaveX(ctx context.Context) *Authorize {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuthorizeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthorizeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuthorizeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := authorize.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AuthorizeUpdateOne) sqlSave(ctx context.Context) (_node *Authorize, err error) {
	_spec := sqlgraph.NewUpdateSpec(authorize.Table, authorize.Columns, sqlgraph.NewFieldSpec(authorize.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Authorize.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authorize.FieldID)
		for _, f := range fields {
			if !authorize.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authorize.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(authorize.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientSecret(); ok {
		_spec.SetField(authorize.FieldClientSecret, field.TypeString, value)
	}
	if value, ok := _u.mutation.GrantType(); ok {
		_spec.SetField(authorize.FieldGrantType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RedirectURI(); ok {
		_spec.SetField(authorize.FieldRedirectURI, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(authorize.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Deleted(); ok {
		_spec.SetField(authorize.FieldDeleted, field.TypeBool, value)
	}
	_node = &Authorize{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authorize.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
