// Code generated by ent, DO NOT EDIT.

package ent

import (
	"teslatrack/internal/data/ent/authorize"
	"teslatrack/internal/data/ent/authorizetoken"
	"teslatrack/internal/data/ent/partner"
	"teslatrack/internal/data/ent/schema"
	"teslatrack/internal/data/ent/user"
	"teslatrack/internal/data/ent/vehicle"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	authorizeFields := schema.Authorize{}.Fields()
	_ = authorizeFields
	// authorizeDescCreatedAt is the schema descriptor for created_at field.
	authorizeDescCreatedAt := authorizeFields[4].Descriptor()
	// authorize.DefaultCreatedAt holds the default value on creation for the created_at field.
	authorize.DefaultCreatedAt = authorizeDescCreatedAt.Default.(func() time.Time)
	// authorizeDescUpdatedAt is the schema descriptor for updated_at field.
	authorizeDescUpdatedAt := authorizeFields[5].Descriptor()
	// authorize.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	authorize.DefaultUpdatedAt = authorizeDescUpdatedAt.Default.(func() time.Time)
	// authorize.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	authorize.UpdateDefaultUpdatedAt = authorizeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// authorizeDescDeleted is the schema descriptor for deleted field.
	authorizeDescDeleted := authorizeFields[6].Descriptor()
	// authorize.DefaultDeleted holds the default value on creation for the deleted field.
	authorize.DefaultDeleted = authorizeDescDeleted.Default.(bool)
	authorizetokenFields := schema.AuthorizeToken{}.Fields()
	_ = authorizetokenFields
	// authorizetokenDescCreatedAt is the schema descriptor for created_at field.
	authorizetokenDescCreatedAt := authorizetokenFields[6].Descriptor()
	// authorizetoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	authorizetoken.DefaultCreatedAt = authorizetokenDescCreatedAt.Default.(func() time.Time)
	// authorizetokenDescUpdatedAt is the schema descriptor for updated_at field.
	authorizetokenDescUpdatedAt := authorizetokenFields[7].Descriptor()
	// authorizetoken.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	authorizetoken.DefaultUpdatedAt = authorizetokenDescUpdatedAt.Default.(func() time.Time)
	// authorizetokenDescDeleted is the schema descriptor for deleted field.
	authorizetokenDescDeleted := authorizetokenFields[8].Descriptor()
	// authorizetoken.DefaultDeleted holds the default value on creation for the deleted field.
	authorizetoken.DefaultDeleted = authorizetokenDescDeleted.Default.(bool)
	partnerFields := schema.Partner{}.Fields()
	_ = partnerFields
	// partnerDescTokenType is the schema descriptor for token_type field.
	partnerDescTokenType := partnerFields[3].Descriptor()
	// partner.TokenTypeValidator is a validator for the "token_type" field. It is called by the builders before save.
	partner.TokenTypeValidator = partnerDescTokenType.Validators[0].(func(string) error)
	// partnerDescCreatedAt is the schema descriptor for created_at field.
	partnerDescCreatedAt := partnerFields[4].Descriptor()
	// partner.DefaultCreatedAt holds the default value on creation for the created_at field.
	partner.DefaultCreatedAt = partnerDescCreatedAt.Default.(func() time.Time)
	// partnerDescUpdatedAt is the schema descriptor for updated_at field.
	partnerDescUpdatedAt := partnerFields[5].Descriptor()
	// partner.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	partner.DefaultUpdatedAt = partnerDescUpdatedAt.Default.(func() time.Time)
	// partner.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	partner.UpdateDefaultUpdatedAt = partnerDescUpdatedAt.UpdateDefault.(func() time.Time)
	// partnerDescDeleted is the schema descriptor for deleted field.
	partnerDescDeleted := partnerFields[6].Descriptor()
	// partner.DefaultDeleted holds the default value on creation for the deleted field.
	partner.DefaultDeleted = partnerDescDeleted.Default.(bool)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescGender is the schema descriptor for gender field.
	userDescGender := userFields[7].Descriptor()
	// user.DefaultGender holds the default value on creation for the gender field.
	user.DefaultGender = userDescGender.Default.(int8)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[10].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[11].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescDeleted is the schema descriptor for deleted field.
	userDescDeleted := userFields[12].Descriptor()
	// user.DefaultDeleted holds the default value on creation for the deleted field.
	user.DefaultDeleted = userDescDeleted.Default.(bool)
	vehicleFields := schema.Vehicle{}.Fields()
	_ = vehicleFields
	// vehicleDescVin is the schema descriptor for vin field.
	vehicleDescVin := vehicleFields[0].Descriptor()
	// vehicle.VinValidator is a validator for the "vin" field. It is called by the builders before save.
	vehicle.VinValidator = vehicleDescVin.Validators[0].(func(string) error)
	// vehicleDescInService is the schema descriptor for in_service field.
	vehicleDescInService := vehicleFields[5].Descriptor()
	// vehicle.DefaultInService holds the default value on creation for the in_service field.
	vehicle.DefaultInService = vehicleDescInService.Default.(int8)
	// vehicleDescCalendarEnabled is the schema descriptor for calendar_enabled field.
	vehicleDescCalendarEnabled := vehicleFields[6].Descriptor()
	// vehicle.DefaultCalendarEnabled holds the default value on creation for the calendar_enabled field.
	vehicle.DefaultCalendarEnabled = vehicleDescCalendarEnabled.Default.(int8)
	// vehicleDescCreatedAt is the schema descriptor for created_at field.
	vehicleDescCreatedAt := vehicleFields[10].Descriptor()
	// vehicle.DefaultCreatedAt holds the default value on creation for the created_at field.
	vehicle.DefaultCreatedAt = vehicleDescCreatedAt.Default.(func() time.Time)
	// vehicleDescUpdatedAt is the schema descriptor for updated_at field.
	vehicleDescUpdatedAt := vehicleFields[11].Descriptor()
	// vehicle.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	vehicle.DefaultUpdatedAt = vehicleDescUpdatedAt.Default.(func() time.Time)
	// vehicle.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	vehicle.UpdateDefaultUpdatedAt = vehicleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// vehicleDescDeleted is the schema descriptor for deleted field.
	vehicleDescDeleted := vehicleFields[12].Descriptor()
	// vehicle.DefaultDeleted holds the default value on creation for the deleted field.
	vehicle.DefaultDeleted = vehicleDescDeleted.Default.(bool)
}
