// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Authorize is the predicate function for authorize builders.
type Authorize func(*sql.Selector)

// AuthorizeToken is the predicate function for authorizetoken builders.
type AuthorizeToken func(*sql.Selector)
