// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: teslatrack/v1/authorize.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message for creating a new authorization client.
type CreateAuthorizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The client identifier. Must be unique.
	ClientId string `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	// The client secret. A confidential value.
	ClientSecret string `protobuf:"bytes,2,opt,name=clientSecret,proto3" json:"clientSecret,omitempty"`
	// The grant type the client is allowed to use (e.g., "authorization_code").
	GrantType string `protobuf:"bytes,3,opt,name=grantType,proto3" json:"grantType,omitempty"`
	// The URI to redirect to after authorization.
	RedirectURI   string `protobuf:"bytes,4,opt,name=redirectURI,proto3" json:"redirectURI,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuthorizeRequest) Reset() {
	*x = CreateAuthorizeRequest{}
	mi := &file_teslatrack_v1_authorize_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuthorizeRequest) ProtoMessage() {}

func (x *CreateAuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teslatrack_v1_authorize_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuthorizeRequest.ProtoReflect.Descriptor instead.
func (*CreateAuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_teslatrack_v1_authorize_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAuthorizeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreateAuthorizeRequest) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *CreateAuthorizeRequest) GetGrantType() string {
	if x != nil {
		return x.GrantType
	}
	return ""
}

func (x *CreateAuthorizeRequest) GetRedirectURI() string {
	if x != nil {
		return x.RedirectURI
	}
	return ""
}

// The reply message containing the ID of the newly created authorization client.
type CreateAuthorizeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuthorizeReply) Reset() {
	*x = CreateAuthorizeReply{}
	mi := &file_teslatrack_v1_authorize_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuthorizeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuthorizeReply) ProtoMessage() {}

func (x *CreateAuthorizeReply) ProtoReflect() protoreflect.Message {
	mi := &file_teslatrack_v1_authorize_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuthorizeReply.ProtoReflect.Descriptor instead.
func (*CreateAuthorizeReply) Descriptor() ([]byte, []int) {
	return file_teslatrack_v1_authorize_proto_rawDescGZIP(), []int{1}
}

type CallbackRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// callback code
	Code          string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackRequest) Reset() {
	*x = CallbackRequest{}
	mi := &file_teslatrack_v1_authorize_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackRequest) ProtoMessage() {}

func (x *CallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teslatrack_v1_authorize_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackRequest.ProtoReflect.Descriptor instead.
func (*CallbackRequest) Descriptor() ([]byte, []int) {
	return file_teslatrack_v1_authorize_proto_rawDescGZIP(), []int{2}
}

func (x *CallbackRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type CallbackReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackReply) Reset() {
	*x = CallbackReply{}
	mi := &file_teslatrack_v1_authorize_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackReply) ProtoMessage() {}

func (x *CallbackReply) ProtoReflect() protoreflect.Message {
	mi := &file_teslatrack_v1_authorize_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackReply.ProtoReflect.Descriptor instead.
func (*CallbackReply) Descriptor() ([]byte, []int) {
	return file_teslatrack_v1_authorize_proto_rawDescGZIP(), []int{3}
}

var File_teslatrack_v1_authorize_proto protoreflect.FileDescriptor

const file_teslatrack_v1_authorize_proto_rawDesc = "" +
	"\n" +
	"\x1dteslatrack/v1/authorize.proto\x12\x11api.teslatrack.v1\x1a\x1cgoogle/api/annotations.proto\"\x98\x01\n" +
	"\x16CreateAuthorizeRequest\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\x12\"\n" +
	"\fclientSecret\x18\x02 \x01(\tR\fclientSecret\x12\x1c\n" +
	"\tgrantType\x18\x03 \x01(\tR\tgrantType\x12 \n" +
	"\vredirectURI\x18\x04 \x01(\tR\vredirectURI\"\x16\n" +
	"\x14CreateAuthorizeReply\"%\n" +
	"\x0fCallbackRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\x0f\n" +
	"\rCallbackReply2\x87\x02\n" +
	"\tAuthorize\x12\x83\x01\n" +
	"\x0fCreateAuthorize\x12).api.teslatrack.v1.CreateAuthorizeRequest\x1a'.api.teslatrack.v1.CreateAuthorizeReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/authorize\x12t\n" +
	"\bCallback\x12\".api.teslatrack.v1.CallbackRequest\x1a .api.teslatrack.v1.CallbackReply\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/authorize/callbackB6\n" +
	"\x11api.teslatrack.v1P\x01Z\x1fteslatrack/api/teslatrack/v1;v1b\x06proto3"

var (
	file_teslatrack_v1_authorize_proto_rawDescOnce sync.Once
	file_teslatrack_v1_authorize_proto_rawDescData []byte
)

func file_teslatrack_v1_authorize_proto_rawDescGZIP() []byte {
	file_teslatrack_v1_authorize_proto_rawDescOnce.Do(func() {
		file_teslatrack_v1_authorize_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_teslatrack_v1_authorize_proto_rawDesc), len(file_teslatrack_v1_authorize_proto_rawDesc)))
	})
	return file_teslatrack_v1_authorize_proto_rawDescData
}

var file_teslatrack_v1_authorize_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_teslatrack_v1_authorize_proto_goTypes = []any{
	(*CreateAuthorizeRequest)(nil), // 0: api.teslatrack.v1.CreateAuthorizeRequest
	(*CreateAuthorizeReply)(nil),   // 1: api.teslatrack.v1.CreateAuthorizeReply
	(*CallbackRequest)(nil),        // 2: api.teslatrack.v1.CallbackRequest
	(*CallbackReply)(nil),          // 3: api.teslatrack.v1.CallbackReply
}
var file_teslatrack_v1_authorize_proto_depIdxs = []int32{
	0, // 0: api.teslatrack.v1.Authorize.CreateAuthorize:input_type -> api.teslatrack.v1.CreateAuthorizeRequest
	2, // 1: api.teslatrack.v1.Authorize.Callback:input_type -> api.teslatrack.v1.CallbackRequest
	1, // 2: api.teslatrack.v1.Authorize.CreateAuthorize:output_type -> api.teslatrack.v1.CreateAuthorizeReply
	3, // 3: api.teslatrack.v1.Authorize.Callback:output_type -> api.teslatrack.v1.CallbackReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_teslatrack_v1_authorize_proto_init() }
func file_teslatrack_v1_authorize_proto_init() {
	if File_teslatrack_v1_authorize_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_teslatrack_v1_authorize_proto_rawDesc), len(file_teslatrack_v1_authorize_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_teslatrack_v1_authorize_proto_goTypes,
		DependencyIndexes: file_teslatrack_v1_authorize_proto_depIdxs,
		MessageInfos:      file_teslatrack_v1_authorize_proto_msgTypes,
	}.Build()
	File_teslatrack_v1_authorize_proto = out.File
	file_teslatrack_v1_authorize_proto_goTypes = nil
	file_teslatrack_v1_authorize_proto_depIdxs = nil
}
