// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: teslatrack/v1/authorize.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthorizeClient is the client API for Authorize service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthorizeClient interface {
	// CreateAuthorize creates a new OAuth 2.0 client configuration.
	// This is typically an administrative operation to register a new client.
	CreateAuthorize(ctx context.Context, in *CreateAuthorizeRequest, opts ...grpc.CallOption) (*CreateAuthorizeReply, error)
	// Redirect generates the authorization URL and redirects the user to the OAuth provider.
	Redirect(ctx context.Context, in *RedirectRequest, opts ...grpc.CallOption) (*RedirectReply, error)
	// Callback is the endpoint that the OAuth provider calls after user authorization.
	// It receives the authorization code needed to exchange for an access token.
	// see: internal/server/mux.go
	Callback(ctx context.Context, in *CallbackRequest, opts ...grpc.CallOption) (*CallbackReply, error)
}

type authorizeClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthorizeClient(cc grpc.ClientConnInterface) AuthorizeClient {
	return &authorizeClient{cc}
}

func (c *authorizeClient) CreateAuthorize(ctx context.Context, in *CreateAuthorizeRequest, opts ...grpc.CallOption) (*CreateAuthorizeReply, error) {
	out := new(CreateAuthorizeReply)
	err := c.cc.Invoke(ctx, "/api.teslatrack.v1.Authorize/CreateAuthorize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizeClient) Redirect(ctx context.Context, in *RedirectRequest, opts ...grpc.CallOption) (*RedirectReply, error) {
	out := new(RedirectReply)
	err := c.cc.Invoke(ctx, "/api.teslatrack.v1.Authorize/Redirect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizeClient) Callback(ctx context.Context, in *CallbackRequest, opts ...grpc.CallOption) (*CallbackReply, error) {
	out := new(CallbackReply)
	err := c.cc.Invoke(ctx, "/api.teslatrack.v1.Authorize/Callback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorizeServer is the server API for Authorize service.
// All implementations must embed UnimplementedAuthorizeServer
// for forward compatibility
type AuthorizeServer interface {
	// CreateAuthorize creates a new OAuth 2.0 client configuration.
	// This is typically an administrative operation to register a new client.
	CreateAuthorize(context.Context, *CreateAuthorizeRequest) (*CreateAuthorizeReply, error)
	// Redirect generates the authorization URL and redirects the user to the OAuth provider.
	Redirect(context.Context, *RedirectRequest) (*RedirectReply, error)
	// Callback is the endpoint that the OAuth provider calls after user authorization.
	// It receives the authorization code needed to exchange for an access token.
	// see: internal/server/mux.go
	Callback(context.Context, *CallbackRequest) (*CallbackReply, error)
	mustEmbedUnimplementedAuthorizeServer()
}

// UnimplementedAuthorizeServer must be embedded to have forward compatible implementations.
type UnimplementedAuthorizeServer struct {
}

func (UnimplementedAuthorizeServer) CreateAuthorize(context.Context, *CreateAuthorizeRequest) (*CreateAuthorizeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAuthorize not implemented")
}
func (UnimplementedAuthorizeServer) Redirect(context.Context, *RedirectRequest) (*RedirectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Redirect not implemented")
}
func (UnimplementedAuthorizeServer) Callback(context.Context, *CallbackRequest) (*CallbackReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Callback not implemented")
}
func (UnimplementedAuthorizeServer) mustEmbedUnimplementedAuthorizeServer() {}

// UnsafeAuthorizeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthorizeServer will
// result in compilation errors.
type UnsafeAuthorizeServer interface {
	mustEmbedUnimplementedAuthorizeServer()
}

func RegisterAuthorizeServer(s grpc.ServiceRegistrar, srv AuthorizeServer) {
	s.RegisterService(&Authorize_ServiceDesc, srv)
}

func _Authorize_CreateAuthorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAuthorizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizeServer).CreateAuthorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.teslatrack.v1.Authorize/CreateAuthorize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizeServer).CreateAuthorize(ctx, req.(*CreateAuthorizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorize_Redirect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedirectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizeServer).Redirect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.teslatrack.v1.Authorize/Redirect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizeServer).Redirect(ctx, req.(*RedirectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorize_Callback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizeServer).Callback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.teslatrack.v1.Authorize/Callback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizeServer).Callback(ctx, req.(*CallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Authorize_ServiceDesc is the grpc.ServiceDesc for Authorize service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Authorize_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.teslatrack.v1.Authorize",
	HandlerType: (*AuthorizeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAuthorize",
			Handler:    _Authorize_CreateAuthorize_Handler,
		},
		{
			MethodName: "Redirect",
			Handler:    _Authorize_Redirect_Handler,
		},
		{
			MethodName: "Callback",
			Handler:    _Authorize_Callback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "teslatrack/v1/authorize.proto",
}
