// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: teslatrack/v1/signup.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message for creating a new signup.
type CreateSignupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user's account.
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// The user's password.
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// The invitation code.
	AskedCode     string `protobuf:"bytes,3,opt,name=asked_code,json=askedCode,proto3" json:"asked_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSignupRequest) Reset() {
	*x = CreateSignupRequest{}
	mi := &file_teslatrack_v1_signup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSignupRequest) ProtoMessage() {}

func (x *CreateSignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teslatrack_v1_signup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSignupRequest.ProtoReflect.Descriptor instead.
func (*CreateSignupRequest) Descriptor() ([]byte, []int) {
	return file_teslatrack_v1_signup_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSignupRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *CreateSignupRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateSignupRequest) GetAskedCode() string {
	if x != nil {
		return x.AskedCode
	}
	return ""
}

// The response message for creating a new signup.
type CreateSignupReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSignupReply) Reset() {
	*x = CreateSignupReply{}
	mi := &file_teslatrack_v1_signup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSignupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSignupReply) ProtoMessage() {}

func (x *CreateSignupReply) ProtoReflect() protoreflect.Message {
	mi := &file_teslatrack_v1_signup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSignupReply.ProtoReflect.Descriptor instead.
func (*CreateSignupReply) Descriptor() ([]byte, []int) {
	return file_teslatrack_v1_signup_proto_rawDescGZIP(), []int{1}
}

// The request message for verifying a signup.
type VerifySignupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user's account to verify.
	Account       string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySignupRequest) Reset() {
	*x = VerifySignupRequest{}
	mi := &file_teslatrack_v1_signup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySignupRequest) ProtoMessage() {}

func (x *VerifySignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teslatrack_v1_signup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySignupRequest.ProtoReflect.Descriptor instead.
func (*VerifySignupRequest) Descriptor() ([]byte, []int) {
	return file_teslatrack_v1_signup_proto_rawDescGZIP(), []int{2}
}

func (x *VerifySignupRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

// The response message for verifying a signup.
type VerifySignupReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates if the account is already registered.
	IsRepeated    bool `protobuf:"varint,1,opt,name=is_repeated,json=isRepeated,proto3" json:"is_repeated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySignupReply) Reset() {
	*x = VerifySignupReply{}
	mi := &file_teslatrack_v1_signup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySignupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySignupReply) ProtoMessage() {}

func (x *VerifySignupReply) ProtoReflect() protoreflect.Message {
	mi := &file_teslatrack_v1_signup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySignupReply.ProtoReflect.Descriptor instead.
func (*VerifySignupReply) Descriptor() ([]byte, []int) {
	return file_teslatrack_v1_signup_proto_rawDescGZIP(), []int{3}
}

func (x *VerifySignupReply) GetIsRepeated() bool {
	if x != nil {
		return x.IsRepeated
	}
	return false
}

var File_teslatrack_v1_signup_proto protoreflect.FileDescriptor

const file_teslatrack_v1_signup_proto_rawDesc = "" +
	"\n" +
	"\x1ateslatrack/v1/signup.proto\x12\x11api.teslatrack.v1\x1a\x1cgoogle/api/annotations.proto\"j\n" +
	"\x13CreateSignupRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"asked_code\x18\x03 \x01(\tR\taskedCode\"\x13\n" +
	"\x11CreateSignupReply\"/\n" +
	"\x13VerifySignupRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\"4\n" +
	"\x11VerifySignupReply\x12\x1f\n" +
	"\vis_repeated\x18\x01 \x01(\bR\n" +
	"isRepeated2\x85\x02\n" +
	"\x06Signup\x12~\n" +
	"\fCreateSignup\x12&.api.teslatrack.v1.CreateSignupRequest\x1a$.api.teslatrack.v1.CreateSignupReply\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/signup/create\x12{\n" +
	"\fVerifySignup\x12&.api.teslatrack.v1.VerifySignupRequest\x1a$.api.teslatrack.v1.VerifySignupReply\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/signup/verifyB6\n" +
	"\x11api.teslatrack.v1P\x01Z\x1fteslatrack/api/teslatrack/v1;v1b\x06proto3"

var (
	file_teslatrack_v1_signup_proto_rawDescOnce sync.Once
	file_teslatrack_v1_signup_proto_rawDescData []byte
)

func file_teslatrack_v1_signup_proto_rawDescGZIP() []byte {
	file_teslatrack_v1_signup_proto_rawDescOnce.Do(func() {
		file_teslatrack_v1_signup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_teslatrack_v1_signup_proto_rawDesc), len(file_teslatrack_v1_signup_proto_rawDesc)))
	})
	return file_teslatrack_v1_signup_proto_rawDescData
}

var file_teslatrack_v1_signup_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_teslatrack_v1_signup_proto_goTypes = []any{
	(*CreateSignupRequest)(nil), // 0: api.teslatrack.v1.CreateSignupRequest
	(*CreateSignupReply)(nil),   // 1: api.teslatrack.v1.CreateSignupReply
	(*VerifySignupRequest)(nil), // 2: api.teslatrack.v1.VerifySignupRequest
	(*VerifySignupReply)(nil),   // 3: api.teslatrack.v1.VerifySignupReply
}
var file_teslatrack_v1_signup_proto_depIdxs = []int32{
	0, // 0: api.teslatrack.v1.Signup.CreateSignup:input_type -> api.teslatrack.v1.CreateSignupRequest
	2, // 1: api.teslatrack.v1.Signup.VerifySignup:input_type -> api.teslatrack.v1.VerifySignupRequest
	1, // 2: api.teslatrack.v1.Signup.CreateSignup:output_type -> api.teslatrack.v1.CreateSignupReply
	3, // 3: api.teslatrack.v1.Signup.VerifySignup:output_type -> api.teslatrack.v1.VerifySignupReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_teslatrack_v1_signup_proto_init() }
func file_teslatrack_v1_signup_proto_init() {
	if File_teslatrack_v1_signup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_teslatrack_v1_signup_proto_rawDesc), len(file_teslatrack_v1_signup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_teslatrack_v1_signup_proto_goTypes,
		DependencyIndexes: file_teslatrack_v1_signup_proto_depIdxs,
		MessageInfos:      file_teslatrack_v1_signup_proto_msgTypes,
	}.Build()
	File_teslatrack_v1_signup_proto = out.File
	file_teslatrack_v1_signup_proto_goTypes = nil
	file_teslatrack_v1_signup_proto_depIdxs = nil
}
