// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v5.29.3
// source: teslatrack/v1/signin.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSigninIdentifier = "/api.teslatrack.v1.Signin/Identifier"

type SigninHTTPServer interface {
	// Identifier Identifier provides a method to sign in with account and password.
	// Maps to HTTP POST /api/v1/signin/identifier
	Identifier(context.Context, *IdentifierRequest) (*IdentifierReply, error)
}

func RegisterSigninHTTPServer(s *http.Server, srv SigninHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/signin/identifier", _Signin_Identifier0_HTTP_Handler(srv))
}

func _Signin_Identifier0_HTTP_Handler(srv SigninHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in IdentifierRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSigninIdentifier)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Identifier(ctx, req.(*IdentifierRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*IdentifierReply)
		return ctx.Result(200, reply)
	}
}

type SigninHTTPClient interface {
	Identifier(ctx context.Context, req *IdentifierRequest, opts ...http.CallOption) (rsp *IdentifierReply, err error)
}

type SigninHTTPClientImpl struct {
	cc *http.Client
}

func NewSigninHTTPClient(client *http.Client) SigninHTTPClient {
	return &SigninHTTPClientImpl{client}
}

func (c *SigninHTTPClientImpl) Identifier(ctx context.Context, in *IdentifierRequest, opts ...http.CallOption) (*IdentifierReply, error) {
	var out IdentifierReply
	pattern := "/api/v1/signin/identifier"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSigninIdentifier))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
