// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: teslatrack/v1/signin.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Signin_Identifier_FullMethodName = "/api.teslatrack.v1.Signin/Identifier"
)

// SigninClient is the client API for Signin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The Signin service definition.
type SigninClient interface {
	// Identifier provides a method to sign in with account and password.
	// Maps to HTTP POST /api/v1/signin/identifier
	Identifier(ctx context.Context, in *IdentifierRequest, opts ...grpc.CallOption) (*IdentifierReply, error)
}

type signinClient struct {
	cc grpc.ClientConnInterface
}

func NewSigninClient(cc grpc.ClientConnInterface) SigninClient {
	return &signinClient{cc}
}

func (c *signinClient) Identifier(ctx context.Context, in *IdentifierRequest, opts ...grpc.CallOption) (*IdentifierReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdentifierReply)
	err := c.cc.Invoke(ctx, Signin_Identifier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SigninServer is the server API for Signin service.
// All implementations must embed UnimplementedSigninServer
// for forward compatibility.
//
// The Signin service definition.
type SigninServer interface {
	// Identifier provides a method to sign in with account and password.
	// Maps to HTTP POST /api/v1/signin/identifier
	Identifier(context.Context, *IdentifierRequest) (*IdentifierReply, error)
	mustEmbedUnimplementedSigninServer()
}

// UnimplementedSigninServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSigninServer struct{}

func (UnimplementedSigninServer) Identifier(context.Context, *IdentifierRequest) (*IdentifierReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Identifier not implemented")
}
func (UnimplementedSigninServer) mustEmbedUnimplementedSigninServer() {}
func (UnimplementedSigninServer) testEmbeddedByValue()                {}

// UnsafeSigninServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SigninServer will
// result in compilation errors.
type UnsafeSigninServer interface {
	mustEmbedUnimplementedSigninServer()
}

func RegisterSigninServer(s grpc.ServiceRegistrar, srv SigninServer) {
	// If the following call pancis, it indicates UnimplementedSigninServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Signin_ServiceDesc, srv)
}

func _Signin_Identifier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentifierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigninServer).Identifier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Signin_Identifier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigninServer).Identifier(ctx, req.(*IdentifierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Signin_ServiceDesc is the grpc.ServiceDesc for Signin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Signin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.teslatrack.v1.Signin",
	HandlerType: (*SigninServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Identifier",
			Handler:    _Signin_Identifier_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "teslatrack/v1/signin.proto",
}
