server:
  http:
    hostname: "https://teslatrack.wallora.top"
    addr: 0.0.0.0:8100
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9100
    timeout: 1s
  mux:
    addr: 0.0.0.0:8101
    timeout: 1s
  tesla:
    callback: /authorize/callback
    redirect_url: /
data:
  # to .env file
  database:
    driver: mysql
    source: root:root@123@tcp(106.15.37.58:3306)/teslatrack?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
