server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
  mux:
    addr: 0.0.0.0:8001
    timeout: 1s
data:
  # to .env file
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/teslatrack?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
