// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AuthorizesColumns holds the columns for the "authorizes" table.
	AuthorizesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// AuthorizesTable holds the schema information for the "authorizes" table.
	AuthorizesTable = &schema.Table{
		Name:       "authorizes",
		Columns:    AuthorizesColumns,
		PrimaryKey: []*schema.Column{AuthorizesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AuthorizesTable,
	}
)

func init() {
}
