// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AuthorizeColumns holds the columns for the "authorize" table.
	AuthorizeColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "client_id", Type: field.TypeString},
		{Name: "client_secret", Type: field.TypeString},
		{Name: "grant_type", Type: field.TypeString},
		{Name: "redirect_uri", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted", Type: field.TypeBool, Default: false},
	}
	// AuthorizeTable holds the schema information for the "authorize" table.
	AuthorizeTable = &schema.Table{
		Name:       "authorize",
		Columns:    AuthorizeColumns,
		PrimaryKey: []*schema.Column{AuthorizeColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AuthorizeTable,
	}
)

func init() {
	AuthorizeTable.Annotation = &entsql.Annotation{
		Table: "authorize",
	}
}
