// Code generated by ent, DO NOT EDIT.

package authorizetoken

import (
	"teslatrack/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldLTE(FieldID, id))
}

// TeslaCode applies equality check predicate on the "tesla_code" field. It's identical to TeslaCodeEQ.
func TeslaCode(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldEQ(FieldTeslaCode, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldEQ(FieldClientID, v))
}

// ClientSecret applies equality check predicate on the "client_secret" field. It's identical to ClientSecretEQ.
func ClientSecret(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldEQ(FieldClientSecret, v))
}

// AccessToken applies equality check predicate on the "access_token" field. It's identical to AccessTokenEQ.
func AccessToken(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldEQ(FieldAccessToken, v))
}

// RefreshToken applies equality check predicate on the "refresh_token" field. It's identical to RefreshTokenEQ.
func RefreshToken(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldEQ(FieldRefreshToken, v))
}

// Scope applies equality check predicate on the "scope" field. It's identical to ScopeEQ.
func Scope(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldEQ(FieldScope, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldEQ(FieldUpdatedAt, v))
}

// Deleted applies equality check predicate on the "deleted" field. It's identical to DeletedEQ.
func Deleted(v bool) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldEQ(FieldDeleted, v))
}

// TeslaCodeEQ applies the EQ predicate on the "tesla_code" field.
func TeslaCodeEQ(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldEQ(FieldTeslaCode, v))
}

// TeslaCodeNEQ applies the NEQ predicate on the "tesla_code" field.
func TeslaCodeNEQ(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldNEQ(FieldTeslaCode, v))
}

// TeslaCodeIn applies the In predicate on the "tesla_code" field.
func TeslaCodeIn(vs ...string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldIn(FieldTeslaCode, vs...))
}

// TeslaCodeNotIn applies the NotIn predicate on the "tesla_code" field.
func TeslaCodeNotIn(vs ...string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldNotIn(FieldTeslaCode, vs...))
}

// TeslaCodeGT applies the GT predicate on the "tesla_code" field.
func TeslaCodeGT(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldGT(FieldTeslaCode, v))
}

// TeslaCodeGTE applies the GTE predicate on the "tesla_code" field.
func TeslaCodeGTE(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldGTE(FieldTeslaCode, v))
}

// TeslaCodeLT applies the LT predicate on the "tesla_code" field.
func TeslaCodeLT(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldLT(FieldTeslaCode, v))
}

// TeslaCodeLTE applies the LTE predicate on the "tesla_code" field.
func TeslaCodeLTE(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldLTE(FieldTeslaCode, v))
}

// TeslaCodeContains applies the Contains predicate on the "tesla_code" field.
func TeslaCodeContains(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldContains(FieldTeslaCode, v))
}

// TeslaCodeHasPrefix applies the HasPrefix predicate on the "tesla_code" field.
func TeslaCodeHasPrefix(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldHasPrefix(FieldTeslaCode, v))
}

// TeslaCodeHasSuffix applies the HasSuffix predicate on the "tesla_code" field.
func TeslaCodeHasSuffix(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldHasSuffix(FieldTeslaCode, v))
}

// TeslaCodeEqualFold applies the EqualFold predicate on the "tesla_code" field.
func TeslaCodeEqualFold(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldEqualFold(FieldTeslaCode, v))
}

// TeslaCodeContainsFold applies the ContainsFold predicate on the "tesla_code" field.
func TeslaCodeContainsFold(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldContainsFold(FieldTeslaCode, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldContainsFold(FieldClientID, v))
}

// ClientSecretEQ applies the EQ predicate on the "client_secret" field.
func ClientSecretEQ(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldEQ(FieldClientSecret, v))
}

// ClientSecretNEQ applies the NEQ predicate on the "client_secret" field.
func ClientSecretNEQ(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldNEQ(FieldClientSecret, v))
}

// ClientSecretIn applies the In predicate on the "client_secret" field.
func ClientSecretIn(vs ...string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldIn(FieldClientSecret, vs...))
}

// ClientSecretNotIn applies the NotIn predicate on the "client_secret" field.
func ClientSecretNotIn(vs ...string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldNotIn(FieldClientSecret, vs...))
}

// ClientSecretGT applies the GT predicate on the "client_secret" field.
func ClientSecretGT(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldGT(FieldClientSecret, v))
}

// ClientSecretGTE applies the GTE predicate on the "client_secret" field.
func ClientSecretGTE(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldGTE(FieldClientSecret, v))
}

// ClientSecretLT applies the LT predicate on the "client_secret" field.
func ClientSecretLT(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldLT(FieldClientSecret, v))
}

// ClientSecretLTE applies the LTE predicate on the "client_secret" field.
func ClientSecretLTE(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldLTE(FieldClientSecret, v))
}

// ClientSecretContains applies the Contains predicate on the "client_secret" field.
func ClientSecretContains(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldContains(FieldClientSecret, v))
}

// ClientSecretHasPrefix applies the HasPrefix predicate on the "client_secret" field.
func ClientSecretHasPrefix(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldHasPrefix(FieldClientSecret, v))
}

// ClientSecretHasSuffix applies the HasSuffix predicate on the "client_secret" field.
func ClientSecretHasSuffix(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldHasSuffix(FieldClientSecret, v))
}

// ClientSecretEqualFold applies the EqualFold predicate on the "client_secret" field.
func ClientSecretEqualFold(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldEqualFold(FieldClientSecret, v))
}

// ClientSecretContainsFold applies the ContainsFold predicate on the "client_secret" field.
func ClientSecretContainsFold(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldContainsFold(FieldClientSecret, v))
}

// AccessTokenEQ applies the EQ predicate on the "access_token" field.
func AccessTokenEQ(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldEQ(FieldAccessToken, v))
}

// AccessTokenNEQ applies the NEQ predicate on the "access_token" field.
func AccessTokenNEQ(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldNEQ(FieldAccessToken, v))
}

// AccessTokenIn applies the In predicate on the "access_token" field.
func AccessTokenIn(vs ...string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldIn(FieldAccessToken, vs...))
}

// AccessTokenNotIn applies the NotIn predicate on the "access_token" field.
func AccessTokenNotIn(vs ...string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldNotIn(FieldAccessToken, vs...))
}

// AccessTokenGT applies the GT predicate on the "access_token" field.
func AccessTokenGT(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldGT(FieldAccessToken, v))
}

// AccessTokenGTE applies the GTE predicate on the "access_token" field.
func AccessTokenGTE(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldGTE(FieldAccessToken, v))
}

// AccessTokenLT applies the LT predicate on the "access_token" field.
func AccessTokenLT(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldLT(FieldAccessToken, v))
}

// AccessTokenLTE applies the LTE predicate on the "access_token" field.
func AccessTokenLTE(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldLTE(FieldAccessToken, v))
}

// AccessTokenContains applies the Contains predicate on the "access_token" field.
func AccessTokenContains(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldContains(FieldAccessToken, v))
}

// AccessTokenHasPrefix applies the HasPrefix predicate on the "access_token" field.
func AccessTokenHasPrefix(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldHasPrefix(FieldAccessToken, v))
}

// AccessTokenHasSuffix applies the HasSuffix predicate on the "access_token" field.
func AccessTokenHasSuffix(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldHasSuffix(FieldAccessToken, v))
}

// AccessTokenEqualFold applies the EqualFold predicate on the "access_token" field.
func AccessTokenEqualFold(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldEqualFold(FieldAccessToken, v))
}

// AccessTokenContainsFold applies the ContainsFold predicate on the "access_token" field.
func AccessTokenContainsFold(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldContainsFold(FieldAccessToken, v))
}

// RefreshTokenEQ applies the EQ predicate on the "refresh_token" field.
func RefreshTokenEQ(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldEQ(FieldRefreshToken, v))
}

// RefreshTokenNEQ applies the NEQ predicate on the "refresh_token" field.
func RefreshTokenNEQ(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldNEQ(FieldRefreshToken, v))
}

// RefreshTokenIn applies the In predicate on the "refresh_token" field.
func RefreshTokenIn(vs ...string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldIn(FieldRefreshToken, vs...))
}

// RefreshTokenNotIn applies the NotIn predicate on the "refresh_token" field.
func RefreshTokenNotIn(vs ...string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldNotIn(FieldRefreshToken, vs...))
}

// RefreshTokenGT applies the GT predicate on the "refresh_token" field.
func RefreshTokenGT(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldGT(FieldRefreshToken, v))
}

// RefreshTokenGTE applies the GTE predicate on the "refresh_token" field.
func RefreshTokenGTE(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldGTE(FieldRefreshToken, v))
}

// RefreshTokenLT applies the LT predicate on the "refresh_token" field.
func RefreshTokenLT(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldLT(FieldRefreshToken, v))
}

// RefreshTokenLTE applies the LTE predicate on the "refresh_token" field.
func RefreshTokenLTE(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldLTE(FieldRefreshToken, v))
}

// RefreshTokenContains applies the Contains predicate on the "refresh_token" field.
func RefreshTokenContains(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldContains(FieldRefreshToken, v))
}

// RefreshTokenHasPrefix applies the HasPrefix predicate on the "refresh_token" field.
func RefreshTokenHasPrefix(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldHasPrefix(FieldRefreshToken, v))
}

// RefreshTokenHasSuffix applies the HasSuffix predicate on the "refresh_token" field.
func RefreshTokenHasSuffix(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldHasSuffix(FieldRefreshToken, v))
}

// RefreshTokenEqualFold applies the EqualFold predicate on the "refresh_token" field.
func RefreshTokenEqualFold(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldEqualFold(FieldRefreshToken, v))
}

// RefreshTokenContainsFold applies the ContainsFold predicate on the "refresh_token" field.
func RefreshTokenContainsFold(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldContainsFold(FieldRefreshToken, v))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldEQ(FieldScope, v))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldNEQ(FieldScope, v))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldIn(FieldScope, vs...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldNotIn(FieldScope, vs...))
}

// ScopeGT applies the GT predicate on the "scope" field.
func ScopeGT(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldGT(FieldScope, v))
}

// ScopeGTE applies the GTE predicate on the "scope" field.
func ScopeGTE(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldGTE(FieldScope, v))
}

// ScopeLT applies the LT predicate on the "scope" field.
func ScopeLT(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldLT(FieldScope, v))
}

// ScopeLTE applies the LTE predicate on the "scope" field.
func ScopeLTE(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldLTE(FieldScope, v))
}

// ScopeContains applies the Contains predicate on the "scope" field.
func ScopeContains(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldContains(FieldScope, v))
}

// ScopeHasPrefix applies the HasPrefix predicate on the "scope" field.
func ScopeHasPrefix(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldHasPrefix(FieldScope, v))
}

// ScopeHasSuffix applies the HasSuffix predicate on the "scope" field.
func ScopeHasSuffix(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldHasSuffix(FieldScope, v))
}

// ScopeEqualFold applies the EqualFold predicate on the "scope" field.
func ScopeEqualFold(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldEqualFold(FieldScope, v))
}

// ScopeContainsFold applies the ContainsFold predicate on the "scope" field.
func ScopeContainsFold(v string) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldContainsFold(FieldScope, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedEQ applies the EQ predicate on the "deleted" field.
func DeletedEQ(v bool) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldEQ(FieldDeleted, v))
}

// DeletedNEQ applies the NEQ predicate on the "deleted" field.
func DeletedNEQ(v bool) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.FieldNEQ(FieldDeleted, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AuthorizeToken) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AuthorizeToken) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AuthorizeToken) predicate.AuthorizeToken {
	return predicate.AuthorizeToken(sql.NotPredicates(p))
}
